Add WithUnprotectedFile() option
AzureAD/microsoft-authentication-extensions-for-dotnet pull request #152
Opened 2021-09-01 20:55 UTC by bgavrilMS

2021-09-02 03:30 UTC, pmaytak requested changes
Questions about protected/unprotected modes mutual exclusivity,

2021-09-02 03:30 UTC, pmaytak commented on src/Shared/StorageCreationProperties.cs
> +        private void Validate(string keyringSecretLabel)
Does `keyringSecretLabel` need to be passed in or can the `KeyringSecretLabel` property be used?

2021-09-02 03:30 UTC, pmaytak commented on src/Shared/StorageCreationProperties.cs
> +            if ((UseLinuxUnencryptedFallback || UseUnencryptedFallback) &&
Is it valid to have plaintext storage on linux but protected on mac or windows?
Is `UseLinuxUnencryptedFallback` then essentially obsolete and superseded by `UseUnencryptedFallback`?

This shows like you can have mixed modes?
https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/0b28722578e7b7263f26fad0cccdf9f0ec48c84b/src/Microsoft.Identity.Client.Extensions.Msal/Storage.cs#L74-L105

2021-09-03 14:27 UTC, bgavrilMS commented on src/Shared/StorageCreationProperties.cs
> +            if ((UseLinuxUnencryptedFallback || UseUnencryptedFallback) &&
Fair point, I will make them mutually exclusive. 
Yes, UseUnencryptedFallback is a superset. There are some very rare cases where encryption does not work on Win and Mac. Only PowerShell seems to bump into them. 

So I'd rather not advertise this new option, and let folks use UseLinuxUnencryptedFallback  instead.

2021-09-04 04:19 UTC, pmaytak approved these changes

2021-09-07 17:04 UTC, pmaytak commented on src/Shared/StorageCreationProperties.cs
> +                throw new ArgumentException("Using Luiplaintext storage is mutually exclusive with other Mac storage options. ");
typo.

2021-09-07 21:18 UTC, merged