Optimized for perf
AzureAD/microsoft-authentication-extensions-for-dotnet pull request #178
Opened 2022-05-18 17:22 UTC by SameerK-MSFT

GetProcess is called only once and formatting is done only once

2022-05-19 19:02 UTC, pmaytak requested changes

2022-05-19 19:02 UTC, pmaytak commented on src/Shared/SharedUtilities.cs
> +        private static readonly Lazy<Process> s_currentProcess = new Lazy<Process>(() => Process.GetCurrentProcess());
Hmm, wondering if there are could be issues to staticly hanging onto a process reference? Recommendation [here](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-6.0#remarks) is to dispose of Process after being used.

Maybe save a string instead something like this?
```suggestion
        private static readonly Lazy<string> s_currentProcessInfo = new Lazy<string>(() => $"{Process.GetCurrentProcess().Id} {Process.GetCurrentProcess().ProcessName}");
```

2022-05-19 19:02 UTC, pmaytak commented on src/Shared/SharedUtilities.cs
> +        public static int GetCurrentProcessId() => s_currentProcess.Value.Id;
internal?

2022-05-20 16:47 UTC, SameerK-MSFT commented on src/Shared/SharedUtilities.cs
> +        private static readonly Lazy<Process> s_currentProcess = new Lazy<Process>(() => Process.GetCurrentProcess());
My thought behind was that this is a static variable. So, the dispose would not be necessary. And keeping it there would help in accessing more properties in the future. I am open either way.

2022-05-20 16:48 UTC, SameerK-MSFT commented on src/Shared/SharedUtilities.cs
> +        public static int GetCurrentProcessId() => s_currentProcess.Value.Id;
This being a utility, public would be good. Anyone can use it.

2022-05-20 22:43 UTC, bgavrilMS commented on src/Shared/SharedUtilities.cs
> +        private static readonly Lazy<Process> s_currentProcess = new Lazy<Process>(() => Process.GetCurrentProcess());
We want to cache a string, not the Process. Seems less risky with what Peter is proposing.

2022-05-20 22:49 UTC, SameerK-MSFT commented on src/Shared/SharedUtilities.cs
> +        private static readonly Lazy<Process> s_currentProcess = new Lazy<Process>(() => Process.GetCurrentProcess());
I think we can cache id and name separately and create string one time before the loop. So Id and process can be with no context in the shared utility and used later by anyone. Creating formatted string before the loop should not be costly. Also, the format can be changed anytime.

2022-05-21 14:50 UTC, bgavrilMS approved these changes

2022-05-21 15:38 UTC, gladjohn approved these changes
looks good @SameerK-MSFT

2022-05-23 15:33 UTC, pmaytak approved these changes
I'm a bit reserved in this perspective - the only change I would make the Get methods internal, and expose them only if there's a specific need by users.

2022-05-23 20:10 UTC, SameerK-MSFT commented
Shows that the pipeline was successful. https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=926323&view=results

2022-05-23 20:11 UTC, merged