Integrating with MSAL's IIdentityLogger
AzureAD/microsoft-authentication-extensions-for-dotnet pull request #190
Opened 2022-08-26 05:07 UTC by trwalke

fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3627

2022-08-26 10:32 UTC, bgavrilMS commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +            LogMessage(args.IdentityLogger, EventLogLevel.Informational, $"Before access");
Should really be "verbose" level

2022-08-26 10:42 UTC, bgavrilMS commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +        private static void LogMessage(IIdentityLogger identityLogger, EventLogLevel level, string message, TraceSourceLogger traceSourceLogger)
I don't see the point in having this method. It only seems used from the method at line 514.

2022-08-26 10:43 UTC, bgavrilMS commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +                        LogMessage(args.IdentityLogger, EventLogLevel.Error, "[Microsoft.Identity.Client.Extensions] An error occured while reading the token cache: " + e, logger);
Having that prefix there is great - can you add it to all messages please? `[Microsoft.Identity.Client.Extensions]`

2022-08-26 10:44 UTC, bgavrilMS requested changes
All Info level msg should really be Verbose
Log actual exceptions or propagate logger (but that would be hard)

2022-08-31 06:15 UTC, trwalke commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +        private static void LogMessage(IIdentityLogger identityLogger, EventLogLevel level, string message, TraceSourceLogger traceSourceLogger)
The method at line 514 is a static method so there is no object reference to use when logging. That is why I added one method for static and an overload that is not.

2022-08-31 06:17 UTC, trwalke commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +            LogMessage(args.IdentityLogger, EventLogLevel.Informational, $"Before access");
ok, changing them to verbose. I'll leave the error level though

2022-08-31 14:22 UTC, bgavrilMS commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +        private static void LogMessage(IIdentityLogger identityLogger, EventLogLevel level, string message, TraceSourceLogger traceSourceLogger)
Ok, I don't see the point in the method at line 518 then :). What's the point of a static if it needs to use an instance member? 

(this is a non-blocking comment)

2022-08-31 14:23 UTC, bgavrilMS approved these changes

2022-08-31 18:26 UTC, pmaytak approved these changes

2022-08-31 18:26 UTC, pmaytak commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +                        LogMessage(args.IdentityLogger, EventLogLevel.Error, "[Microsoft.Identity.Client.Extensions] Deleting the token cache as it might be corrupt.", logger);
the prefix is not needed, since it's added in LogMessage method.

2022-08-31 18:26 UTC, pmaytak commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +            LogMessage(args.IdentityLogger, EventLogLevel.Verbose, $"Acquiring lock for token cache");
I would maybe combine the consecutive log lines with the same log level to improve perf (maybe add NewLine if needed too).

2022-08-31 21:10 UTC, trwalke commented on src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
> +        private static void LogMessage(IIdentityLogger identityLogger, EventLogLevel level, string message, TraceSourceLogger traceSourceLogger)
So both methods arent 100% needed. Its just the method one line 514 reduces the need to pass in one additional variable which makes the code look a little bit cleaner.

2022-09-01 05:28 UTC, merged